### ISSUE TITLE
Links para Twitter, Face etc. na interface

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/revoada#12]
Adicionar plugin WP?

**Comment by tamielbr** [comment]
O "like" está como contador, mas indo para uma página vazio. como temos um bom número de likes,sSugiro @robsonsampaio criar a página no FB e ficar como administrador. Passando o link eu adiciono na página. Vale?

**Comment by tamielbr** [comment]
Twitter já adicionado (topo da página).

**Comment by tamielbr** [comment]
@robsonsampaio conseguiu agilizar o FB? Precisa de alguma ajuda?

**Comment by robsonsampaio** [comment]
Ola Tel, está ok o face - https://www.facebook.com/pages/Revoada/701809509908911

**Comment by tamielbr** [comment]
Adicionado no site (topo superior direito).
