### ISSUE TITLE
Novo servidor para projetos

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/revoada#20]
Jovem Hacker, Revoada, Agência, Mapa da Cultura, Lime Survey

**Comment by tamielbr** [comment]
Importante que ele rode Omeka para o Mapa. 
Gosto do http://asmallorange.com/, mas é EUA.
Sempre podemos usar http://digitalocean.com/, mas não dará trabalho.

**Comment by gabrielfedel** [comment]
Pela sugestão do Robson de tentar trabalhar fora dos EUA, eu acho que podemos tentar esse: https://www.orangewebsite.com/offshore-hosting.php e se vermos que não rola mudamos. Fazemos um teste de 1 ou 2 meses, o quê acham? o Omeka não é pra ter problema em rolar lá, ele não exige grandes recursos

**Comment by tamielbr** [comment]
@gabrielfedel, quando contratar, fecha esse aqui?

**Comment by robsonsampaio** [comment]
Blz.


Abs

2015-02-06 3:11 GMT-02:00 Tel <notifications@github.com>:

> @gabrielfedel <https://github.com/gabrielfedel>, quando contratar, fecha
> esse aqui?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tamielbr/revoada/issues/20#issuecomment-73183914>.
>



-- 
Robson B. Sampaio***

Artista Visual/Fotografo
Gnu/Linux user # 489500
e-mail: reductio.ad.ethos@gmail.com
skype: rbscamba1
twitter: @rbscamba
facebook: robson.sampaio1 <http://www.facebook.com/robson.sampaio1>

http://lattes.cnpq.br/7461730442638498
<http://lattes.cnpq.br/7461730442638498>
http://www.flickr.com/photos/robson_b_sampaio/collections/
http://robsonbsampaio.tumblr.com

<http://culturadigital.br/robsonbsampaio/>"A mente que se abre a uma nova
idéia jamais voltará ao seu tamanho original." Albert Einstein

**Comment by gabrielfedel** [comment]
Ó, eu ia contratar mas fiquei bem em dúvida,
o que eu queria (o orangewebsite) nos planos mais básicos tem limitação de domínios (o quê eu acho ruim pra gente, que de cara temos uns 3)

ia pro 1984, servidor compartilhado, que sai 7 dólares por mês, o que acha?

**Comment by tamielbr** [comment]
Lendo no FAQ: "Users pay for one year in advance. If for some reason you want to quit before the year is out you can cancel your hosting and ask us to refund the months remaining." São 130 doletas pelo ano. Não sei se roda Omeka nele (não achei Softaculous por lá, que garante que funciona). Só preocupações...

**Comment by gabrielfedel** [comment]
é...

tem o servidor dedicado, mas sai uns 30 dólares por mês
está difícil de decidir

**Comment by tamielbr** [comment]
Não sei o que @robsonsampaio acha, mas pagar um ano me parece fria, como não conhecemos o serviço... O outro é caro, e retorna o problema de ter que configurar email, etc. que havíamos descartado. Vale mais um esforço para descobrir o que colegas tão usando? Acho que tá todo mundo na UOL host ;)

**Comment by gabrielfedel** [comment]
Posso tentar dar mais uma pesquisada... o 1984 foi o quê me recomendaram, o outro que achei foi no search mesmo
esse uol host é bom?
tem algum bom serviço no Brasil será?

**Comment by gabrielfedel** [comment]
Eu ia instalar o lime survey agora, mas desanimei pois é mais uma coisa pra migrar depois...
O ideal seria a gente ter 1 servidor compartilhado e 1 vps, pensando aqui, colocando as coisas mais simples no compartilhado e os sistemas (omeka, lime survey, etc) no vps

mas pode ser um plano futuro

**Comment by robsonsampaio** [comment]
Ola meninos, veja que é melhor para nós, pq pagar mais um ano sem pelo
menos sabermos como é a estrutura, vai ser osso.

Abs

Em 13 de fevereiro de 2015 15:32, Gabriel Fedel <notifications@github.com>
escreveu:

> Posso tentar dar mais uma pesquisada... o 1984 foi o quê me recomendaram,
> o outro que achei foi no search mesmo
> esse uol host é bom?
> tem algum bom serviço no Brasil será?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tamielbr/revoada/issues/20#issuecomment-74292389>.
>



-- 
Robson B. Sampaio***

Artista Visual/Fotografo
Gnu/Linux user # 489500
e-mail: reductio.ad.ethos@gmail.com
skype: rbscamba1
twitter: @rbscamba
facebook: robson.sampaio1 <http://www.facebook.com/robson.sampaio1>

http://lattes.cnpq.br/7461730442638498
<http://lattes.cnpq.br/7461730442638498>
http://www.flickr.com/photos/robson_b_sampaio/collections/
http://robsonbsampaio.tumblr.com

<http://culturadigital.br/robsonbsampaio/>"A mente que se abre a uma nova
idéia jamais voltará ao seu tamanho original." Albert Einstein

**Comment by tamielbr** [comment]
@gabrielfedel  Eu acho que se não rolar um externo que seja bom, eu iria com o ASO (asmallorange.com) que fuciona bem e tem tudo o que precisamos, pelo preço. Mas eu topo dar mais 1 semana pra encontrar outro servidor (razoável?). VPS vai ser problema pra nós por hora, pelo preço. Pode ser pouco, mas vai começar custar e vamos ter que tirar do bolso. Podemos usar os VPS de projetos e pessoais que temos pra experimentar, e no futuro juntar tudo num bom serviço, quando houver grana.

**Comment by tamielbr** [comment]
@gabrielfedel e Canadá? Vi esse por exemplo, que tem Softaculous, sem contrato. http://www.canadianwebhosting.com/hosting/linux_hosting.asp Não vi com mais cuidado, mas pode ser interessante. Que acha?

**Comment by gabrielfedel** [comment]
Esse fim de semana conversei com um pessoal do LHC, e o problema do Canadá é que apesar das leis serem melhores, eles tem um acordo com os EUA que se houver pedido eles repassam os dados

O pessoal sugeriu a França, essa empresa : https://www.ovh.pt/ tem servidores lá
tem bastante opção, o quê acha de tentarmos nesse?

**Comment by robsonsampaio** [comment]
Vamos tentar então a França Fedel!

Abs

Em 23 de fevereiro de 2015 12:06, Gabriel Fedel <notifications@github.com>
escreveu:

> Esse fim de semana conversei com um pessoal do LHC, e o problema do Canadá
> é que apesar das leis serem melhores, eles tem um acordo com os EUA que se
> houver pedido eles repassam os dados
>
> O pessoal sugeriu a França, essa empresa : https://www.ovh.pt/ tem
> servidores lá
> tem bastante opção, o quê acha de tentarmos nesse?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tamielbr/revoada/issues/20#issuecomment-75558116>.
>



-- 
Robson B. Sampaio***

Artista Visual/Fotografo
Gnu/Linux user # 489500
e-mail: reductio.ad.ethos@gmail.com
skype: rbscamba1
twitter: @rbscamba
facebook: robson.sampaio1 <http://www.facebook.com/robson.sampaio1>

http://lattes.cnpq.br/7461730442638498
<http://lattes.cnpq.br/7461730442638498>
http://www.flickr.com/photos/robson_b_sampaio/collections/
http://robsonbsampaio.tumblr.com

<http://culturadigital.br/robsonbsampaio/>"A mente que se abre a uma nova
idéia jamais voltará ao seu tamanho original." Albert Einstein

**Comment by gabrielfedel** [comment]
@tamielbr , estou achando melhor pegarmos um VPS, pois conseguimos ter mais opção de serviços (e aí tentamos resolver o email nele mesmo), o quê acha?

**Comment by tamielbr** [comment]
Eu topo tentar o dedicado, mas pelo que você falou o custo é alto (uns 80 reais por mês). Acho que por hora vai ser muito pesado (teríamos que arranjar 1000 por ano). Se esse (OVH) não rodar Omeka, podemos usar seu domínio temporariamente ou outro que tenho disponível só pra isso, e eventualmente fazemos uma substituição.

**Comment by gabrielfedel** [comment]
opa, ó tel:
http://www.ovh.pt/vps/vps-classic.xml

tá uns 2,45 euros por mês, acho que o preço tá dentro (saí mais barato que o digital ocean)

**Comment by tamielbr** [comment]
Acho que vale experimentar um mês e ver. Pelo menos 3 wordpress já vão pra lá (Revoada, JH, Alivre). O mapa, a gente vê se consegue instalar. Que tal?

**Comment by gabrielfedel** [comment]
Acho ótimo. Provavelmente a única coisa que vai ficar difícil por hora é o email, já vou comprar então.
Esse plano dá direito à 1 domínio grátis, precisamos de algum ?

**Comment by tamielbr** [comment]
Email difícil? Tá incluido no plano... podemos incluir só um falae@revoada.net.br por hora. Depois criamos um pros outros projetos. Quanto ao domínio, podíamos ter um pros dados abertos, mas acho muito trampo ter outro agora ;) @robsonsampaio alguma idéia?

**Comment by gabrielfedel** [comment]
Opa @tamielbr , neste plano?
http://www.ovh.pt/vps/vps-classic.xml
?

não ví email, normalmente as vps não tem email já pré-configurado

**Comment by tamielbr** [comment]
Ah, eu tava vendo esse: http://www.ovh.pt/alojamento-partilhado/alojamento-partilhado-pessoal.xml. Acho que vale a pena o VPS, quero aprender também. Podemos retomar a idéia de marcar em março um "sprint" e chamamos alguém que saiba bem de Postfix e possa nos ensinar a botar o servidor de email no ar, e o que mais quisermos. Vale? O upgrade pro próximo nível  não é mal (15 reais). Eu topo.

**Comment by gabrielfedel** [comment]
ótimo!
vou contratar 1 mês para começar a migração aos poucos e já sentirmos como fluí
acho que o acesso vai ficar mais rápido, pois os sites que estão no meu server agora estão em singapura

**Comment by gabrielfedel** [comment]
Contratado o servidor, 
já migrei os sites  do revoada, jovem hacker, e questionários
estou monitorando pra ver se está tudo ok, aparentemente está tudo tranquilo!

**Comment by robsonsampaio** [comment]
ok
