### ISSUE TITLE
Criar conta no Vimeo

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/revoada#21]
@robsonsampaio vai criar em janeiro.

**Comment by tamielbr** [comment]
Acho que esse tem que fazer. Não temos "banda" nem servidor para servir streaming. Concordam @gabrielfedel @robsonsampaio ?

**Comment by robsonsampaio** [comment]
Ola pessoal, criei o album no flickr https://www.flickr.com/photos/coletivo_revoada/, eu passo o logo e a senha por outro meio.
Tel, vc tinha ficado de criar o Vimeo, ou era eu?

Abs

**Comment by tamielbr** [comment]
era você (veja ao lado "assignee" com o seu nome). abs!

**Comment by robsonsampaio** [comment]
Ok, já faço

**Comment by robsonsampaio** [comment]
Pronto, aqui está o vimeo do Revoada https://vimeo.com/revoada

Faltou mais alguma coisa, que eu tinha ficado como responsável?

**Comment by tamielbr** [comment]
Beleza. vou fechar essa issue e criar um link lá na página. Pra saber tudo o que está no seu nome, é só clicar no seu nome e aparece ;) Valeu!
