### ISSUE TITLE
Conta no Flickr

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/revoada#22]

**Comment by tamielbr** [comment]
Incorporar fotos https://nuvem.fedel.net.br/public.php?service=files&t=f5e788987fa599ffc09dd3624713ecb7

**Comment by robsonsampaio** [comment]
Massa Tel.

2015-03-27 14:48 GMT-03:00 Tel <notifications@github.com>:

> Incorporar fotos
> https://nuvem.fedel.net.br/public.php?service=files&t=f5e788987fa599ffc09dd3624713ecb7
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tamielbr/revoada/issues/22#issuecomment-87031201>.
>



-- 
Robson B. Sampaio***

Artista Visual/Fotografo
Gnu/Linux user # 489500
e-mail: reductio.ad.ethos@gmail.com
skype: rbscamba1
twitter: @rbscamba
facebook: robson.sampaio1 <http://www.facebook.com/robson.sampaio1>

http://lattes.cnpq.br/7461730442638498
<http://lattes.cnpq.br/7461730442638498>
http://www.flickr.com/photos/robson_b_sampaio/collections/
http://robsonbsampaio.tumblr.com

<http://culturadigital.br/robsonbsampaio/>"A mente que se abre a uma nova
idéia jamais voltará ao seu tamanho original." Albert Einstein

**Comment by tamielbr** [comment]
@robsonsampaio poderia criar? infelizmente precisa de um email Yahoo, mas acho que ainda é o melhor sistema que podemos usar, considerando plugins para WP que já usamos. Eu já usei http://piwigo.org/ e achei nem bom - PHP, simples e parece ter plugin WP - https://wordpress.org/plugins/piwigomedia/

**Comment by robsonsampaio** [comment]
Ola pessoal, eu crio o flickr daqui a pouco e coloco aqui.

**Comment by robsonsampaio** [comment]
Feito https://www.flickr.com/photos/coletivo_revoada/, amanhã faço migração de todas fotos que tenho no meu album das nossas atividades

**Comment by tamielbr** [comment]
Adicionado no site.
