### ISSUE TITLE
Redesign do site

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/revoada#24]
Se quisermos esse template (http://educacaoaberta.org/) eu conheço bem e podemos fazer rapidamente.

**Comment by robsonsampaio** [comment]
Sim, eu acho mais interessante o design dele do que estamos usando.

Abs
Em 30/01/2015 16:12, "Tel" <notifications@github.com> escreveu:

**Comment by tamielbr** [comment]
Valeu. 
@gabrielfedel O que pensa? Vamos botar isso pra votação então na semana que vem. Meu receio em usar mais um tema novo é que a curva de aprendizado pra customização acaba sendo maior.

**Comment by gabrielfedel** [comment]
Opa, por mim pode ser gente! o tema é clean e legal!

**Comment by tamielbr** [comment]
Vamos propor então na reunião (5/fev) e se todos toparem, eu faço a troca e começamos a rascunhar.

**Comment by robsonsampaio** [comment]
sim

2015-02-02 14:14 GMT-02:00 Tel <notifications@github.com>:

> Vamos propor então na reunião (5/fev) e se todos toparem, eu faço a troca
> e começamos a rascunhar.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tamielbr/revoada/issues/24#issuecomment-72484350>.
>



-- 
Robson B. Sampaio***

Artista Visual/Fotografo
Gnu/Linux user # 489500
e-mail: reductio.ad.ethos@gmail.com
skype: rbscamba1
twitter: @rbscamba
facebook: robson.sampaio1 <http://www.facebook.com/robson.sampaio1>

http://lattes.cnpq.br/7461730442638498
<http://lattes.cnpq.br/7461730442638498>
http://www.flickr.com/photos/robson_b_sampaio/collections/
http://robsonbsampaio.tumblr.com

<http://culturadigital.br/robsonbsampaio/>"A mente que se abre a uma nova
idéia jamais voltará ao seu tamanho original." Albert Einstein

**Comment by tamielbr** [comment]
Atualizei para o Pinboard. Vamos fazendo ajustes. Vou arrumar algumas coisas no CSS ao longo de março.

**Comment by tamielbr** [comment]
Finalizado por hora. Vamos ajustando. Acho que ficou bem melhor.
