### ISSUE TITLE
Escolher espaço de reunião

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/revoada#27]
Appear.in (limitação de usuários)
Algum canal de áudio confiável?

**Comment by gabrielfedel** [comment]
Fazer testes com o mumble http://mumble.sourceforge.net/

**Comment by tamielbr** [comment]
Appear.in definitvamente é ruim. O Mozilla, funciona bem?

**Comment by tamielbr** [comment]
Tá funcionando bem. Sugiro manter o mumble por hora. Vou fechar isso aqui.
